//! Codegen tests for tomc

use tomc::codegen::{Backend, CodeGenerator, CodegenConfig};
use tomc::lexer::Lexer;
use tomc::parser::TomiParser;

/// Helper to compile tomi.u source to Rust
fn compile_to_rust(source: &str) -> String {
    let mut lexer = Lexer::new(source);
    let tokens = lexer.tokenize().expect("Lexer should succeed");
    let mut parser = TomiParser::new(tokens).with_source(source.to_string());
    let module = parser.parse().expect("Parser should succeed");
    
    let generator = CodeGenerator::new(Backend::Rust);
    generator.generate(&module).expect("Codegen should succeed")
}

/// Helper to compile without header comments
fn compile_to_rust_no_header(source: &str) -> String {
    let mut lexer = Lexer::new(source);
    let tokens = lexer.tokenize().expect("Lexer should succeed");
    let mut parser = TomiParser::new(tokens).with_source(source.to_string());
    let module = parser.parse().expect("Parser should succeed");
    
    let config = CodegenConfig {
        include_comments: false,
        ..CodegenConfig::default()
    };
    let generator = CodeGenerator::with_config(Backend::Rust, config);
    generator.generate(&module).expect("Codegen should succeed")
}

// ═══════════════════════════════════════════════════════════════════════
// Basic Codegen Tests
// ═══════════════════════════════════════════════════════════════════════

#[test]
fn test_empty_module() {
    let rust = compile_to_rust("");
    assert!(rust.contains("// Generated by tomc"));
}

#[test]
fn test_config_no_header() {
    let rust = compile_to_rust_no_header("");
    assert!(!rust.contains("// Generated"));
}

// ═══════════════════════════════════════════════════════════════════════
// Function Codegen Tests
// ═══════════════════════════════════════════════════════════════════════

#[test]
fn test_simple_function() {
    let source = "def hello():\n    return 0\n";
    let rust = compile_to_rust_no_header(source);
    
    assert!(rust.contains("fn hello()"));
    assert!(rust.contains("return 0"));
}

#[test]
fn test_function_with_return_type() {
    let source = "def get_value() -> i32:\n    return 42\n";
    let rust = compile_to_rust_no_header(source);
    
    assert!(rust.contains("fn get_value() -> i32"));
    assert!(rust.contains("return 42"));
}

#[test]
fn test_function_with_params() {
    let source = "def add(a: i32, b: i32) -> i32:\n    return a + b\n";
    let rust = compile_to_rust_no_header(source);
    
    assert!(rust.contains("fn add(a: i32, b: i32) -> i32"));
    assert!(rust.contains("return (a + b)"));
}

#[test]
fn test_public_function() {
    let source = "pub def public_fn():\n    return 1\n";
    let rust = compile_to_rust_no_header(source);
    
    assert!(rust.contains("pub fn public_fn()"));
}

#[test]
fn test_async_function() {
    let source = "async def fetch():\n    return 1\n";
    let rust = compile_to_rust_no_header(source);
    
    assert!(rust.contains("async fn fetch()"));
}

#[test]
fn test_entrypoint_becomes_main() {
    let source = "@entrypoint\ndef start():\n    return 0\n";
    let rust = compile_to_rust_no_header(source);
    
    // @entrypoint should rename the function to main
    assert!(rust.contains("fn main()"));
}

// ═══════════════════════════════════════════════════════════════════════
// Struct Codegen Tests
// ═══════════════════════════════════════════════════════════════════════

#[test]
fn test_simple_struct() {
    let source = "struct Point:\n    x: i32\n    y: i32\n";
    let rust = compile_to_rust_no_header(source);
    
    // Should have derive attributes
    assert!(rust.contains("#[derive(Debug, Clone)]"));
    assert!(rust.contains("struct Point"));
    assert!(rust.contains("x: i32"));
    assert!(rust.contains("y: i32"));
}

#[test]
fn test_public_struct() {
    let source = "pub struct Public:\n    value: i32\n";
    let rust = compile_to_rust_no_header(source);
    
    assert!(rust.contains("pub struct Public"));
}

#[test]
fn test_struct_init() {
    let source = "def test():\n    let p = Point { x: 10, y: 20 }\n";
    let rust = compile_to_rust_no_header(source);
    
    assert!(rust.contains("Point { x: 10, y: 20 }"));
}

// ═══════════════════════════════════════════════════════════════════════
// Enum Codegen Tests
// ═══════════════════════════════════════════════════════════════════════

#[test]
fn test_simple_enum() {
    let source = "enum Color:\n    Red\n    Green\n    Blue\n";
    let rust = compile_to_rust_no_header(source);
    
    // Current implementation derives Debug, Clone
    assert!(rust.contains("#[derive(Debug, Clone)]"));
    assert!(rust.contains("enum Color"));
    assert!(rust.contains("Red"));
    assert!(rust.contains("Green"));
    assert!(rust.contains("Blue"));
}

// ═══════════════════════════════════════════════════════════════════════
// Statement Codegen Tests
// ═══════════════════════════════════════════════════════════════════════

#[test]
fn test_let_statement() {
    let source = "def test():\n    let x = 42\n";
    let rust = compile_to_rust_no_header(source);
    
    assert!(rust.contains("let x = 42"));
}

#[test]
fn test_let_mut_statement() {
    let source = "def test():\n    let mut x = 0\n";
    let rust = compile_to_rust_no_header(source);
    
    assert!(rust.contains("let mut x = 0"));
}

#[test]
fn test_let_with_type() {
    let source = "def test():\n    let x: i32 = 42\n";
    let rust = compile_to_rust_no_header(source);
    
    assert!(rust.contains("let x: i32 = 42"));
}

#[test]
fn test_return_statement() {
    let source = "def test():\n    return 42\n";
    let rust = compile_to_rust_no_header(source);
    
    assert!(rust.contains("return 42"));
}

// ═══════════════════════════════════════════════════════════════════════
// Expression Codegen Tests
// ═══════════════════════════════════════════════════════════════════════

#[test]
fn test_arithmetic_expressions() {
    let source = "def test():\n    let a = 1 + 2\n    let b = 3 - 4\n    let c = 5 * 6\n    let d = 7 / 8\n";
    let rust = compile_to_rust_no_header(source);
    
    assert!(rust.contains("(1 + 2)") || rust.contains("1 + 2"));
    assert!(rust.contains("(3 - 4)") || rust.contains("3 - 4"));
    assert!(rust.contains("(5 * 6)") || rust.contains("5 * 6"));
    assert!(rust.contains("(7 / 8)") || rust.contains("7 / 8"));
}

#[test]
fn test_comparison_expressions() {
    let source = "def test():\n    let a = 1 < 2\n    let b = 3 > 4\n    let c = 5 == 6\n    let d = 7 != 8\n";
    let rust = compile_to_rust_no_header(source);
    
    assert!(rust.contains("1 < 2") || rust.contains("(1 < 2)"));
    assert!(rust.contains("3 > 4") || rust.contains("(3 > 4)"));
    assert!(rust.contains("5 == 6") || rust.contains("(5 == 6)"));
    assert!(rust.contains("7 != 8") || rust.contains("(7 != 8)"));
}

#[test]
fn test_logical_expressions() {
    let source = "def test():\n    let a = true && false\n    let b = true || false\n";
    let rust = compile_to_rust_no_header(source);
    
    assert!(rust.contains("&&"));
    assert!(rust.contains("||"));
}

#[test]
fn test_function_call() {
    let source = "def test():\n    print(x, y)\n";
    let rust = compile_to_rust_no_header(source);
    
    assert!(rust.contains("print(x, y)"));
}

#[test]
fn test_method_call() {
    let source = "def test():\n    obj.method()\n";
    let rust = compile_to_rust_no_header(source);
    
    assert!(rust.contains("obj.method()"));
}

#[test]
fn test_field_access() {
    let source = "def test():\n    let x = point.x\n";
    let rust = compile_to_rust_no_header(source);
    
    assert!(rust.contains("point.x"));
}

#[test]
fn test_array_index() {
    let source = "def test():\n    let x = arr[0]\n";
    let rust = compile_to_rust_no_header(source);
    
    assert!(rust.contains("arr[0]"));
}

// ═══════════════════════════════════════════════════════════════════════
// Control Flow Codegen Tests
// ═══════════════════════════════════════════════════════════════════════

#[test]
fn test_if_statement() {
    let source = "def test():\n    if x > 0:\n        return 1\n";
    let rust = compile_to_rust_no_header(source);
    
    assert!(rust.contains("if"));
    assert!(rust.contains("return 1"));
}

#[test]
fn test_if_else_statement() {
    let source = "def test():\n    if x > 0:\n        return 1\n    else:\n        return 0\n";
    let rust = compile_to_rust_no_header(source);
    
    assert!(rust.contains("if"));
    assert!(rust.contains("else"));
    assert!(rust.contains("return 1"));
    assert!(rust.contains("return 0"));
}

#[test]
fn test_while_loop() {
    let source = "def test():\n    while true:\n        break\n";
    let rust = compile_to_rust_no_header(source);
    
    assert!(rust.contains("while true"));
    assert!(rust.contains("break"));
}

#[test]
fn test_loop() {
    let source = "def test():\n    loop:\n        break\n";
    let rust = compile_to_rust_no_header(source);
    
    assert!(rust.contains("loop"));
    assert!(rust.contains("break"));
}

// ═══════════════════════════════════════════════════════════════════════
// Type Translation Tests
// ═══════════════════════════════════════════════════════════════════════

#[test]
#[ignore = "Generic type syntax not yet implemented in parser"]
fn test_optional_type() {
    let source = "def test(x: Optional<i32>):\n    return 0\n";
    let rust = compile_to_rust_no_header(source);
    
    // Optional<T> should become Option<T> in Rust
    assert!(rust.contains("Option<i32>"));
}

#[test]
#[ignore = "Array type syntax not yet implemented in parser"]
fn test_array_type() {
    let source = "def test(arr: [i32]):\n    return 0\n";
    let rust = compile_to_rust_no_header(source);
    
    // [T] should become Vec<T> in Rust
    assert!(rust.contains("Vec<i32>"));
}

#[test]
fn test_str_type() {
    let source = "def test(s: str):\n    return 0\n";
    let rust = compile_to_rust_no_header(source);
    
    // Currently tomi.u str maps directly to Rust str (not String)
    // Note: This may need updating if we want str -> String conversion
    assert!(rust.contains("str"));
}

// ═══════════════════════════════════════════════════════════════════════
// Backend Tests
// ═══════════════════════════════════════════════════════════════════════

#[test]
fn test_backend_extension() {
    assert_eq!(Backend::Rust.extension(), "rs");
}

#[test]
fn test_backend_name() {
    assert_eq!(Backend::Rust.name(), "Rust");
}

// ═══════════════════════════════════════════════════════════════════════
// Complex Example Tests
// ═══════════════════════════════════════════════════════════════════════

#[test]
fn test_hello_world_program() {
    let source = r#"
@entrypoint
def main():
    let message = "Hello, World!"
    print(message)
"#;
    let rust = compile_to_rust_no_header(source);
    
    assert!(rust.contains("fn main()"));
    assert!(rust.contains("let message = \"Hello, World!\""));
    assert!(rust.contains("print(message)"));
}

#[test]
fn test_struct_with_methods() {
    let source = r#"
struct Point:
    x: i32
    y: i32

def add(a: i32, b: i32) -> i32:
    return a + b

@entrypoint
def main():
    let p = Point { x: 10, y: 20 }
    let sum = add(p.x, p.y)
"#;
    let rust = compile_to_rust_no_header(source);
    
    assert!(rust.contains("struct Point"));
    assert!(rust.contains("fn add(a: i32, b: i32) -> i32"));
    assert!(rust.contains("fn main()"));
    assert!(rust.contains("Point { x: 10, y: 20 }"));
    assert!(rust.contains("add(p.x, p.y)"));
}
