//! Python codegen tests for tomc

use tomc::codegen::{Backend, CodeGenerator, CodegenConfig};
use tomc::lexer::Lexer;
use tomc::parser::TomiParser;

/// Helper to compile tomi.u source to Python
fn compile_to_python(source: &str) -> String {
    let mut lexer = Lexer::new(source);
    let tokens = lexer.tokenize().expect("Lexer should succeed");
    let mut parser = TomiParser::new(tokens).with_source(source.to_string());
    let module = parser.parse().expect("Parser should succeed");

    let generator = CodeGenerator::new(Backend::Python);
    generator.generate(&module).expect("Codegen should succeed")
}

/// Helper to compile without header comments
fn compile_to_python_no_header(source: &str) -> String {
    let mut lexer = Lexer::new(source);
    let tokens = lexer.tokenize().expect("Lexer should succeed");
    let mut parser = TomiParser::new(tokens).with_source(source.to_string());
    let module = parser.parse().expect("Parser should succeed");

    let config = CodegenConfig { include_comments: false, ..CodegenConfig::default() };
    let generator = CodeGenerator::with_config(Backend::Python, config);
    generator.generate(&module).expect("Codegen should succeed")
}

// ═══════════════════════════════════════════════════════════════════════
// Basic Codegen Tests
// ═══════════════════════════════════════════════════════════════════════

#[test]
fn test_empty_module() {
    let py = compile_to_python("");
    assert!(py.contains("# Generated by tomc"));
    assert!(py.contains("from __future__ import annotations"));
}

#[test]
fn test_config_no_header() {
    let py = compile_to_python_no_header("");
    assert!(!py.contains("# Generated"));
    assert!(py.contains("from __future__ import annotations"));
}

#[test]
fn test_runtime_support_imported() {
    let py = compile_to_python_no_header("");
    assert!(py.contains("import sys as _sys"));
}

// ═══════════════════════════════════════════════════════════════════════
// Function Codegen Tests
// ═══════════════════════════════════════════════════════════════════════

#[test]
fn test_simple_function() {
    let source = "def hello():\n    return 0\n";
    let py = compile_to_python_no_header(source);

    assert!(py.contains("def hello()"));
    assert!(py.contains("return 0"));
}

#[test]
fn test_function_with_return_type() {
    let source = "def get_value() -> Int32:\n    return 42\n";
    let py = compile_to_python_no_header(source);

    assert!(py.contains("def get_value() -> int"));
    assert!(py.contains("return 42"));
}

#[test]
fn test_function_with_params() {
    let source = "def add(a: Int32, b: Int32) -> Int32:\n    return a + b\n";
    let py = compile_to_python_no_header(source);

    assert!(py.contains("def add(a: int, b: int) -> int"));
    assert!(py.contains("return (a + b)"));
}

#[test]
fn test_async_function() {
    let source = "async def fetch():\n    return 1\n";
    let py = compile_to_python_no_header(source);

    assert!(py.contains("async def fetch()"));
}

#[test]
fn test_entrypoint_becomes_main() {
    let source = "@entrypoint\ndef start():\n    return 0\n";
    let py = compile_to_python_no_header(source);

    assert!(py.contains("def main()"));
    assert!(py.contains("if __name__ == \"__main__\":"));
    assert!(py.contains("main()"));
}

// ═══════════════════════════════════════════════════════════════════════
// Type Mapping Tests
// ═══════════════════════════════════════════════════════════════════════

#[test]
fn test_int_types_map_to_int() {
    let source = "def f(a: Int8, b: Int16, c: Int32, d: Int64):\n    return a\n";
    let py = compile_to_python_no_header(source);

    assert!(py.contains("a: int"));
    assert!(py.contains("b: int"));
    assert!(py.contains("c: int"));
    assert!(py.contains("d: int"));
}

#[test]
fn test_uint_types_map_to_int() {
    let source = "def f(a: UInt8, b: UInt16, c: UInt32, d: UInt64):\n    return a\n";
    let py = compile_to_python_no_header(source);

    // All unsigned int types should map to Python int
    assert!(py.contains("a: int"));
    assert!(py.contains("d: int"));
}

#[test]
fn test_float_types_map_to_float() {
    let source = "def f(a: Float32, b: Float64):\n    return a\n";
    let py = compile_to_python_no_header(source);

    assert!(py.contains("a: float"));
    assert!(py.contains("b: float"));
}

#[test]
fn test_bool_type_maps_to_bool() {
    let source = "def f(a: Bool) -> Bool:\n    return a\n";
    let py = compile_to_python_no_header(source);

    assert!(py.contains("a: bool"));
    assert!(py.contains("-> bool"));
}

#[test]
fn test_string_type_maps_to_str() {
    let source = "def f(s: String) -> String:\n    return s\n";
    let py = compile_to_python_no_header(source);

    assert!(py.contains("s: str"));
    assert!(py.contains("-> str"));
}

#[test]
fn test_bytes_type_maps_to_bytes() {
    let source = "def f(b: Bytes) -> Bytes:\n    return b\n";
    let py = compile_to_python_no_header(source);

    assert!(py.contains("b: bytes"));
    assert!(py.contains("-> bytes"));
}

// ═══════════════════════════════════════════════════════════════════════
// Literal Tests
// ═══════════════════════════════════════════════════════════════════════

#[test]
fn test_bool_literals_capitalised() {
    let source = "def f():\n    let x = true\n    let y = false\n";
    let py = compile_to_python_no_header(source);

    assert!(py.contains("x = True"));
    assert!(py.contains("y = False"));
}

#[test]
fn test_int_literal() {
    let source = "def f():\n    let x = 42\n";
    let py = compile_to_python_no_header(source);
    assert!(py.contains("x = 42"));
}

#[test]
fn test_float_literal() {
    let source = "def f():\n    let x = 3.14\n";
    let py = compile_to_python_no_header(source);
    assert!(py.contains("x = 3.14"));
}

#[test]
fn test_string_literal() {
    let source = "def f():\n    let x = \"hello\"\n";
    let py = compile_to_python_no_header(source);
    assert!(py.contains("x = \"hello\""));
}

// ═══════════════════════════════════════════════════════════════════════
// Operator Tests
// ═══════════════════════════════════════════════════════════════════════

#[test]
fn test_logical_operators() {
    let source = "def f():\n    let x = true and false\n    let y = true or false\n";
    let py = compile_to_python_no_header(source);

    // tomi.u && → Python "and"
    assert!(py.contains("and"));
    assert!(py.contains("or"));
}

#[test]
fn test_not_operator() {
    let source = "def f():\n    let x = not true\n";
    let py = compile_to_python_no_header(source);

    assert!(py.contains("not True"));
}

#[test]
fn test_comparison_operators() {
    let source = "def f():\n    let a = 1 == 2\n    let b = 1 != 2\n    let c = 1 < 2\n    let d = 1 <= 2\n    let e = 1 > 2\n    let f2 = 1 >= 2\n";
    let py = compile_to_python_no_header(source);

    assert!(py.contains("=="));
    assert!(py.contains("!="));
    assert!(py.contains("< 2"));
    assert!(py.contains("<= 2"));
    assert!(py.contains("> 2"));
    assert!(py.contains(">= 2"));
}

#[test]
fn test_arithmetic_operators() {
    let source =
        "def f():\n    let a = 1 + 2\n    let b = 3 - 1\n    let c = 2 * 3\n    let d = 10 % 3\n";
    let py = compile_to_python_no_header(source);

    assert!(py.contains("+"));
    assert!(py.contains("-"));
    assert!(py.contains("*"));
    assert!(py.contains("%"));
}

// ═══════════════════════════════════════════════════════════════════════
// Statement Tests
// ═══════════════════════════════════════════════════════════════════════

#[test]
fn test_let_statement() {
    let source = "def f():\n    let x = 10\n";
    let py = compile_to_python_no_header(source);
    assert!(py.contains("x = 10"));
}

#[test]
fn test_let_with_type_annotation() {
    let source = "def f():\n    let x: Int32 = 10\n";
    let py = compile_to_python_no_header(source);
    assert!(py.contains("x: int = 10"));
}

#[test]
fn test_assignment() {
    let source = "def f():\n    mut x = 0\n    x = 5\n";
    let py = compile_to_python_no_header(source);
    assert!(py.contains("x = 0"));
    assert!(py.contains("x = 5"));
}

#[test]
fn test_compound_assignment() {
    let source = "def f():\n    mut x = 0\n    x += 1\n    x -= 2\n    x *= 3\n";
    let py = compile_to_python_no_header(source);
    assert!(py.contains("x += 1"));
    assert!(py.contains("x -= 2"));
    assert!(py.contains("x *= 3"));
}

#[test]
fn test_return_statement() {
    let source = "def f():\n    return 42\n";
    let py = compile_to_python_no_header(source);
    assert!(py.contains("return 42"));
}

#[test]
fn test_return_no_value() {
    let source = "def f():\n    return\n";
    let py = compile_to_python_no_header(source);
    assert!(py.contains("return"));
}

// ═══════════════════════════════════════════════════════════════════════
// Control Flow Tests
// ═══════════════════════════════════════════════════════════════════════

#[test]
fn test_while_loop() {
    let source = "def f():\n    mut x = 0\n    while x < 10:\n        x += 1\n";
    let py = compile_to_python_no_header(source);
    assert!(py.contains("while (x < 10):"));
}

#[test]
fn test_for_loop() {
    let source = "def f(xs: [Int32]):\n    for x in xs:\n        let _ = x\n";
    let py = compile_to_python_no_header(source);
    assert!(py.contains("for x in xs:"));
}

#[test]
fn test_break_continue() {
    let source = "def f():\n    loop:\n        break\n";
    let py = compile_to_python_no_header(source);
    assert!(py.contains("while True:"));
    assert!(py.contains("break"));
}

// ═══════════════════════════════════════════════════════════════════════
// Struct/Class Tests
// ═══════════════════════════════════════════════════════════════════════

#[test]
fn test_struct_becomes_dataclass() {
    let source = "struct Point:\n    x: Float64\n    y: Float64\n";
    let py = compile_to_python_no_header(source);

    assert!(py.contains("@dataclass"));
    assert!(py.contains("class Point:"));
    assert!(py.contains("x: float"));
    assert!(py.contains("y: float"));
}

#[test]
fn test_dataclass_import_added() {
    let source = "struct Foo:\n    bar: Int32\n";
    let py = compile_to_python_no_header(source);

    assert!(py.contains("from dataclasses import dataclass"));
}

#[test]
fn test_struct_init() {
    let source = "struct Point:\n    x: Float64\n    y: Float64\n\ndef f():\n    let p = Point { x: 1.0, y: 2.0 }\n";
    let py = compile_to_python_no_header(source);

    assert!(py.contains("Point(x=1.0, y=2.0)"));
}

// ═══════════════════════════════════════════════════════════════════════
// Enum Tests
// ═══════════════════════════════════════════════════════════════════════

#[test]
fn test_simple_enum() {
    let source = "enum Color:\n    Red\n    Green\n    Blue\n";
    let py = compile_to_python_no_header(source);

    assert!(py.contains("class Color(Enum):"));
    assert!(py.contains("Red = auto()"));
    assert!(py.contains("Green = auto()"));
    assert!(py.contains("Blue = auto()"));
}

#[test]
fn test_enum_import_added() {
    let source = "enum Direction:\n    Up\n    Down\n";
    let py = compile_to_python_no_header(source);
    assert!(py.contains("from enum import Enum, auto"));
}

// ═══════════════════════════════════════════════════════════════════════
// Exception Handling Tests
// ═══════════════════════════════════════════════════════════════════════

#[test]
fn test_try_except() {
    let source = "def f():\n    try:\n        let x = 1\n    catch e:\n        let y = 2\n";
    let py = compile_to_python_no_header(source);

    assert!(py.contains("try:"));
    assert!(py.contains("except"));
}

// ═══════════════════════════════════════════════════════════════════════
// Expression Tests
// ═══════════════════════════════════════════════════════════════════════

#[test]
fn test_function_call() {
    let source = "def f():\n    print(42)\n";
    let py = compile_to_python_no_header(source);
    assert!(py.contains("print(42)"));
}

#[test]
fn test_method_call() {
    let source = "def f():\n    let x = \"hello\"\n    x.upper()\n";
    let py = compile_to_python_no_header(source);
    assert!(py.contains("x.upper()"));
}

#[test]
fn test_array_literal() {
    let source = "def f():\n    let xs = [1, 2, 3]\n";
    let py = compile_to_python_no_header(source);
    assert!(py.contains("[1, 2, 3]"));
}

#[test]
fn test_tuple_literal() {
    let source = "def f():\n    let t = (1, 2, 3)\n";
    let py = compile_to_python_no_header(source);
    assert!(py.contains("(1, 2, 3)"));
}

#[test]
fn test_index_expression() {
    let source = "def f():\n    let xs = [1, 2, 3]\n    let x = xs[0]\n";
    let py = compile_to_python_no_header(source);
    assert!(py.contains("xs[0]"));
}

#[test]
fn test_field_access() {
    let source = "struct Point:\n    x: Float64\n    y: Float64\n\ndef f():\n    let p = Point { x: 1.0, y: 2.0 }\n    let v = p.x\n";
    let py = compile_to_python_no_header(source);
    assert!(py.contains("p.x"));
}

#[test]
fn test_lambda() {
    let source = "def f():\n    let double = 2\n";
    let py = compile_to_python_no_header(source);
    assert!(py.contains("double = 2"));
}

// ═══════════════════════════════════════════════════════════════════════
// Const and Type Alias Tests
// ═══════════════════════════════════════════════════════════════════════

#[test]
fn test_const_declaration() {
    let source = "const MAX: Int32 = 100\n";
    let py = compile_to_python_no_header(source);
    assert!(py.contains("MAX: int = 100"));
}

#[test]
fn test_type_alias() {
    let source = "type Id = Int64\n";
    let py = compile_to_python_no_header(source);
    assert!(py.contains("Id = int"));
}

// ═══════════════════════════════════════════════════════════════════════
// Trait / Protocol Tests
// ═══════════════════════════════════════════════════════════════════════

#[test]
fn test_trait_becomes_protocol() {
    let source = "trait Drawable:\n    def draw(self):\n        return 0\n";
    let py = compile_to_python_no_header(source);

    assert!(py.contains("class Drawable(Protocol):"));
    assert!(py.contains("def draw(self)"));
}

#[test]
fn test_protocol_import_added() {
    let source = "trait Readable:\n    def read(self):\n        return 0\n";
    let py = compile_to_python_no_header(source);
    assert!(py.contains("Protocol"));
}
