// Generated by tomc - the tomi.u compiler
// Do not edit manually

#[derive(Debug, Clone)]
struct Point {
    x: i32,
    y: i32,
}

fn add(a: i32, b: i32) -> i32 {
        return (a + b);
}

fn main() {
        let p = Point { x: 10, y: 20 };
        let sum = add(p.x, p.y);
}

