//! Rust code generation backend for tomi.u
//!
//! This module translates tomi.u AST to valid Rust source code.
//!
//! ## Translation Rules
//!
//! | tomi.u          | Rust                |
//! |-----------------|---------------------|
//! | `fn name()`     | `fn name()`         |
//! | `let x = ...`   | `let x = ...`       |
//! | `mut x`         | `let mut x`         |
//! | `struct S`      | `struct S`          |
//! | `enum E`        | `enum E`            |
//! | `trait T`       | `trait T`           |
//! | `impl T for S`  | `impl T for S`      |
//! | `@entrypoint`   | `fn main()`         |
//! | `?Type`         | `Option<Type>`      |
//! | `&T`            | `&T`                |
//! | `&mut T`        | `&mut T`            |

use crate::ast::*;
use crate::codegen::{BackendCodegen, CodeWriter, CodegenConfig};
use crate::error::CompileError;

/// Rust backend for code generation.
pub struct RustBackend {
    /// Configuration options
    config: CodegenConfig,
    /// Output writer
    writer: CodeWriter,
    /// Whether we're inside an async context
    in_async: bool,
    /// Current function being generated
    current_function: Option<String>,
}

impl RustBackend {
    /// Create a new Rust backend.
    pub fn new() -> Self {
        Self {
            config: CodegenConfig::default(),
            writer: CodeWriter::new(),
            in_async: false,
            current_function: None,
        }
    }

    /// Reset the writer for a new generation.
    fn reset(&mut self) {
        self.writer = CodeWriter::with_indent(&self.config.indent);
        self.in_async = false;
        self.current_function = None;
    }

    /// Generate imports at the top of the file.
    fn generate_prelude(&mut self) {
        if self.config.include_comments {
            self.writer
                .writeln("// Generated by tomc - the tomi.u compiler");
            self.writer.writeln("// Do not edit manually");
            self.writer.blank_line();
        }
        // tomi.u built-in function shims
        self.writer.writeln("#[allow(dead_code, unused_variables)]");
        self.writer.writeln("#[inline(always)]");
        self.writer
            .writeln("fn print(args: impl std::fmt::Display) { println!(\"{}\", args); }");
        self.writer.blank_line();
    }

    /// Map tomi.u visibility to Rust.
    fn visibility_to_rust(&self, vis: &Visibility) -> &'static str {
        match vis {
            Visibility::Public => "pub ",
            Visibility::Private => "",
        }
    }

    /// Map tomi.u operator to Rust.
    fn binary_op_to_rust(&self, op: &BinaryOp) -> &'static str {
        match op {
            BinaryOp::Add => "+",
            BinaryOp::Sub => "-",
            BinaryOp::Mul => "*",
            BinaryOp::Div => "/",
            BinaryOp::Mod => "%",
            BinaryOp::Eq => "==",
            BinaryOp::Ne => "!=",
            BinaryOp::Lt => "<",
            BinaryOp::Le => "<=",
            BinaryOp::Gt => ">",
            BinaryOp::Ge => ">=",
            BinaryOp::And => "&&",
            BinaryOp::Or => "||",
            BinaryOp::BitAnd => "&",
            BinaryOp::BitOr => "|",
            BinaryOp::BitXor => "^",
            BinaryOp::Shl => "<<",
            BinaryOp::Shr => ">>",
        }
    }

    /// Map tomi.u unary operator to Rust.
    fn unary_op_to_rust(&self, op: &UnaryOp) -> &'static str {
        match op {
            UnaryOp::Not => "!",
            UnaryOp::Neg => "-",
            UnaryOp::BitNot => "!",
            UnaryOp::Ref => "&",
            UnaryOp::MutRef => "&mut ",
            UnaryOp::Deref => "*",
        }
    }

    /// Map tomi.u assignment operator to Rust.
    fn assign_op_to_rust(&self, op: &AssignOp) -> &'static str {
        match op {
            AssignOp::Assign => "=",
            AssignOp::AddAssign => "+=",
            AssignOp::SubAssign => "-=",
            AssignOp::MulAssign => "*=",
            AssignOp::DivAssign => "/=",
            AssignOp::ModAssign => "%=",
            AssignOp::ShlAssign => "<<=",
            AssignOp::ShrAssign => ">>=",
        }
    }

    /// Check if a decorator is an entrypoint.
    fn has_entrypoint(&self, decorators: &[Decorator]) -> bool {
        decorators
            .iter()
            .any(|d| d.name.node.as_str() == "entrypoint")
    }

    /// Generate generic type parameters.
    fn generate_type_params(&mut self, params: &[TypeParam]) -> Result<(), CompileError> {
        if params.is_empty() {
            return Ok(());
        }

        self.writer.write("<");
        for (i, param) in params.iter().enumerate() {
            if i > 0 {
                self.writer.write(", ");
            }
            self.writer.write(&param.name.node);
            if !param.bounds.is_empty() {
                self.writer.write(": ");
                for (j, bound) in param.bounds.iter().enumerate() {
                    if j > 0 {
                        self.writer.write(" + ");
                    }
                    let bound_str = self.generate_type_path(bound)?;
                    self.writer.write(&bound_str);
                }
            }
        }
        self.writer.write(">");
        Ok(())
    }

    /// Generate where clause if needed.
    fn generate_where_clause(&mut self, params: &[TypeParam]) -> Result<(), CompileError> {
        let has_complex_bounds = params.iter().any(|p| p.bounds.len() > 1);
        if !has_complex_bounds {
            return Ok(());
        }

        self.writer.writeln("");
        self.writer.write("where");
        self.writer.indent();
        for param in params {
            if param.bounds.len() > 1 {
                self.writer.newline();
                self.writer.write(&param.name.node);
                self.writer.write(": ");
                for (i, bound) in param.bounds.iter().enumerate() {
                    if i > 0 {
                        self.writer.write(" + ");
                    }
                    let bound_str = self.generate_type_path(bound)?;
                    self.writer.write(&bound_str);
                }
                self.writer.write(",");
            }
        }
        self.writer.dedent();
        Ok(())
    }

    /// Generate function parameters.
    fn generate_params(&mut self, params: &[Param]) -> Result<(), CompileError> {
        self.writer.write("(");
        for (i, param) in params.iter().enumerate() {
            if i > 0 {
                self.writer.write(", ");
            }

            // Handle self parameter
            if param.name.node == "self" {
                if param.is_mut {
                    self.writer.write("&mut self");
                } else {
                    self.writer.write("&self");
                }
                continue;
            }

            if param.is_mut {
                self.writer.write("mut ");
            }
            self.writer.write(&param.name.node);
            self.writer.write(": ");
            let ty_str = self.generate_type(&param.ty)?;
            self.writer.write(&ty_str);
        }
        self.writer.write(")");
        Ok(())
    }

    /// Generate an import statement.
    fn generate_import(&mut self, import: &Import) -> Result<(), CompileError> {
        self.writer.write("use ");

        // Build the path from Spanned strings
        let path_parts: Vec<&str> = import.path.iter().map(|s| s.node.as_str()).collect();
        let path_str = path_parts.join("::");
        self.writer.write(&path_str);

        // Handle specific items
        if let Some(items) = &import.items {
            self.writer.write("::{");
            for (i, item) in items.iter().enumerate() {
                if i > 0 {
                    self.writer.write(", ");
                }
                self.writer.write(&item.node);
            }
            self.writer.write("}");
        } else if let Some(alias) = &import.alias {
            self.writer.write(" as ");
            self.writer.write(&alias.node);
        }

        self.writer.writeln(";");
        Ok(())
    }

    /// Generate a trait definition.
    fn generate_trait_def(&mut self, t: &Trait) -> Result<(), CompileError> {
        let vis = self.visibility_to_rust(&t.visibility);
        self.writer.write(vis);
        self.writer.write("trait ");
        self.writer.write(&t.name.node);
        self.generate_type_params(&t.type_params)?;

        // Supertraits
        if !t.bounds.is_empty() {
            self.writer.write(": ");
            for (i, bound) in t.bounds.iter().enumerate() {
                if i > 0 {
                    self.writer.write(" + ");
                }
                let bound_str = self.generate_type_path(bound)?;
                self.writer.write(&bound_str);
            }
        }

        self.writer.writeln(" {");
        self.writer.indent();

        for item in &t.items {
            self.generate_trait_item(item)?;
        }

        self.writer.dedent();
        self.writer.writeln("}");
        Ok(())
    }

    /// Generate a trait item.
    fn generate_trait_item(&mut self, item: &TraitItem) -> Result<(), CompileError> {
        match item {
            TraitItem::Method(m) => {
                if m.is_async {
                    self.writer.write("async ");
                }
                self.writer.write("fn ");
                self.writer.write(&m.name.node);
                self.generate_type_params(&m.type_params)?;
                self.generate_params(&m.params)?;

                if let Some(ret) = &m.return_type {
                    self.writer.write(" -> ");
                    let ret_str = self.generate_type(ret)?;
                    self.writer.write(&ret_str);
                }

                // Empty body = trait method declaration (no default impl)
                if m.body.stmts.is_empty() {
                    self.writer.writeln(";");
                } else {
                    self.writer.writeln(" {");
                    self.writer.indent();
                    let block_str = self.generate_block(&m.body)?;
                    self.writer.write(&block_str);
                    self.writer.dedent();
                    self.writer.writeln("}");
                }
            }
            TraitItem::Type { name, bounds, .. } => {
                self.writer.write("type ");
                self.writer.write(&name.node);
                if !bounds.is_empty() {
                    self.writer.write(": ");
                    for (i, bound) in bounds.iter().enumerate() {
                        if i > 0 {
                            self.writer.write(" + ");
                        }
                        let bound_str = self.generate_type_path(bound)?;
                        self.writer.write(&bound_str);
                    }
                }
                self.writer.writeln(";");
            }
        }
        Ok(())
    }

    /// Generate an impl block.
    fn generate_impl_block(&mut self, i: &Impl) -> Result<(), CompileError> {
        self.writer.write("impl");
        self.generate_type_params(&i.type_params)?;
        self.writer.write(" ");

        if let Some(trait_path) = &i.trait_path {
            let trait_str = self.generate_type_path(trait_path)?;
            self.writer.write(&trait_str);
            self.writer.write(" for ");
        }

        let self_str = self.generate_type(&i.target)?;
        self.writer.write(&self_str);
        self.writer.writeln(" {");
        self.writer.indent();

        for method in &i.items {
            let func_str = self.generate_function(method)?;
            self.writer.write(&func_str);
            self.writer.blank_line();
        }

        self.writer.dedent();
        self.writer.writeln("}");
        Ok(())
    }

    /// Generate a type alias.
    fn generate_type_alias_item(&mut self, ta: &TypeAlias) -> Result<(), CompileError> {
        let vis_str = self.visibility_to_rust(&ta.visibility);
        self.writer.write(vis_str);
        self.writer.write("type ");
        self.writer.write(&ta.name.node);
        self.generate_type_params(&ta.type_params)?;
        self.writer.write(" = ");
        let ty_str = self.generate_type(&ta.ty)?;
        self.writer.write(&ty_str);
        self.writer.writeln(";");
        Ok(())
    }

    /// Generate a const definition.
    fn generate_const_item(&mut self, c: &Const) -> Result<(), CompileError> {
        let vis_str = self.visibility_to_rust(&c.visibility);
        self.writer.write(vis_str);
        self.writer.write("const ");
        self.writer.write(&c.name.node);
        if let Some(ty) = &c.ty {
            self.writer.write(": ");
            let ty_str = self.generate_type(ty)?;
            self.writer.write(&ty_str);
        }
        self.writer.write(" = ");
        let val_str = self.generate_expr(&c.value)?;
        self.writer.write(&val_str);
        self.writer.writeln(";");
        Ok(())
    }
}

impl Default for RustBackend {
    fn default() -> Self {
        Self::new()
    }
}

impl BackendCodegen for RustBackend {
    fn generate_module(&mut self, module: &Module) -> Result<String, CompileError> {
        self.reset();
        self.generate_prelude();

        // Generate imports
        for import in &module.imports {
            self.generate_import(import)?;
        }

        if !module.imports.is_empty() {
            self.writer.blank_line();
        }

        // Generate items
        for item in &module.items {
            let item_str = self.generate_item(item)?;
            self.writer.write(&item_str);
            self.writer.blank_line();
        }

        Ok(self.writer.take())
    }

    fn generate_item(&mut self, item: &Item) -> Result<String, CompileError> {
        let mut writer = CodeWriter::with_indent(&self.config.indent);
        std::mem::swap(&mut self.writer, &mut writer);

        match item {
            Item::Function(f) => {
                let func_str = self.generate_function(f)?;
                self.writer.write(&func_str);
            }
            Item::Struct(s) => {
                let struct_str = self.generate_struct(s)?;
                self.writer.write(&struct_str);
            }
            Item::Enum(e) => {
                let enum_str = self.generate_enum(e)?;
                self.writer.write(&enum_str);
            }
            Item::Trait(t) => {
                self.generate_trait_def(t)?;
            }
            Item::Impl(i) => {
                self.generate_impl_block(i)?;
            }
            Item::TypeAlias(ta) => {
                self.generate_type_alias_item(ta)?;
            }
            Item::Const(c) => {
                self.generate_const_item(c)?;
            }
        }

        std::mem::swap(&mut self.writer, &mut writer);
        Ok(writer.finish())
    }

    fn generate_function(&mut self, func: &Function) -> Result<String, CompileError> {
        let mut writer = CodeWriter::with_indent(&self.config.indent);
        std::mem::swap(&mut self.writer, &mut writer);

        self.current_function = Some(func.name.node.clone());

        // Check for @entrypoint decorator
        let is_entrypoint = self.has_entrypoint(&func.decorators);

        let vis = self.visibility_to_rust(&func.visibility);
        if !is_entrypoint {
            self.writer.write(vis);
        }

        if func.is_async {
            self.writer.write("async ");
            self.in_async = true;
        }

        self.writer.write("fn ");
        if is_entrypoint {
            self.writer.write("main");
        } else {
            self.writer.write(&func.name.node);
        }

        self.generate_type_params(&func.type_params)?;
        self.generate_params(&func.params)?;

        if let Some(ret_ty) = &func.return_type {
            self.writer.write(" -> ");
            let ret_str = self.generate_type(ret_ty)?;
            self.writer.write(&ret_str);
        }

        self.generate_where_clause(&func.type_params)?;

        self.writer.writeln(" {");
        self.writer.indent();
        let block_str = self.generate_block(&func.body)?;
        self.writer.write(&block_str);
        self.writer.dedent();
        self.writer.writeln("}");

        self.in_async = false;
        self.current_function = None;
        std::mem::swap(&mut self.writer, &mut writer);
        Ok(writer.finish())
    }

    fn generate_struct(&mut self, s: &Struct) -> Result<String, CompileError> {
        let mut writer = CodeWriter::with_indent(&self.config.indent);
        std::mem::swap(&mut self.writer, &mut writer);

        // Derive common traits
        self.writer.writeln("#[derive(Debug, Clone)]");

        let vis = self.visibility_to_rust(&s.visibility);
        self.writer.write(vis);
        self.writer.write("struct ");
        self.writer.write(&s.name.node);
        self.generate_type_params(&s.type_params)?;

        if s.fields.is_empty() {
            self.writer.writeln(";");
        } else {
            self.writer.writeln(" {");
            self.writer.indent();

            for field in &s.fields {
                let field_vis = self.visibility_to_rust(&field.visibility);
                self.writer.write(field_vis);
                self.writer.write(&field.name.node);
                self.writer.write(": ");
                let ty_str = self.generate_type(&field.ty)?;
                self.writer.write(&ty_str);
                self.writer.writeln(",");
            }

            self.writer.dedent();
            self.writer.writeln("}");
        }

        std::mem::swap(&mut self.writer, &mut writer);
        Ok(writer.finish())
    }

    fn generate_enum(&mut self, e: &Enum) -> Result<String, CompileError> {
        let mut writer = CodeWriter::with_indent(&self.config.indent);
        std::mem::swap(&mut self.writer, &mut writer);

        // Derive common traits
        self.writer.writeln("#[derive(Debug, Clone)]");

        let vis = self.visibility_to_rust(&e.visibility);
        self.writer.write(vis);
        self.writer.write("enum ");
        self.writer.write(&e.name.node);
        self.generate_type_params(&e.type_params)?;
        self.writer.writeln(" {");
        self.writer.indent();

        for variant in &e.variants {
            self.writer.write(&variant.name.node);
            match &variant.data {
                VariantData::Unit => {}
                VariantData::Tuple(types) => {
                    self.writer.write("(");
                    for (i, ty) in types.iter().enumerate() {
                        if i > 0 {
                            self.writer.write(", ");
                        }
                        let ty_str = self.generate_type(ty)?;
                        self.writer.write(&ty_str);
                    }
                    self.writer.write(")");
                }
                VariantData::Struct(fields) => {
                    self.writer.writeln(" {");
                    self.writer.indent();
                    for field in fields {
                        self.writer.write(&field.name.node);
                        self.writer.write(": ");
                        let ty_str = self.generate_type(&field.ty)?;
                        self.writer.write(&ty_str);
                        self.writer.writeln(",");
                    }
                    self.writer.dedent();
                    self.writer.write("}");
                }
            }
            self.writer.writeln(",");
        }

        self.writer.dedent();
        self.writer.writeln("}");

        std::mem::swap(&mut self.writer, &mut writer);
        Ok(writer.finish())
    }

    fn generate_type(&mut self, ty: &Type) -> Result<String, CompileError> {
        let result = match ty {
            Type::Named(path) => self.generate_type_path(path)?,
            Type::Generic(path, args) => {
                let path_str = self.generate_type_path(path)?;
                let args_str: Result<Vec<_>, _> =
                    args.iter().map(|t| self.generate_type(t)).collect();
                format!("{}<{}>", path_str, args_str?.join(", "))
            }
            Type::Reference { is_mut, inner } => {
                let inner_str = self.generate_type(inner)?;
                if *is_mut {
                    format!("&mut {}", inner_str)
                } else {
                    format!("&{}", inner_str)
                }
            }
            Type::Optional(inner) => {
                let inner_str = self.generate_type(inner)?;
                format!("Option<{}>", inner_str)
            }
            Type::Tuple(types) => {
                let types_str: Result<Vec<_>, _> =
                    types.iter().map(|t| self.generate_type(t)).collect();
                format!("({})", types_str?.join(", "))
            }
            Type::Array { element, size } => {
                let inner = self.generate_type(element)?;
                if let Some(size) = size {
                    let size_str = self.generate_expr(size)?;
                    format!("[{}; {}]", inner, size_str)
                } else {
                    format!("Vec<{}>", inner)
                }
            }
            Type::Slice(inner) => {
                let inner_str = self.generate_type(inner)?;
                format!("[{}]", inner_str)
            }
            Type::Function {
                params,
                return_type,
            } => {
                let params_str: Result<Vec<_>, _> =
                    params.iter().map(|t| self.generate_type(t)).collect();
                let ret = self.generate_type(return_type)?;
                format!("fn({}) -> {}", params_str?.join(", "), ret)
            }
            Type::Unit => "()".to_string(),
            Type::Never => "!".to_string(),
            Type::Infer => "_".to_string(),
        };
        Ok(result)
    }

    fn generate_type_path(&mut self, path: &TypePath) -> Result<String, CompileError> {
        let segments: Vec<&str> = path.segments.iter().map(|s| s.node.as_str()).collect();
        Ok(segments.join("::"))
    }

    fn generate_expr(&mut self, expr: &Expr) -> Result<String, CompileError> {
        let result = match expr {
            Expr::IntLiteral { value, .. } => value.to_string(),
            Expr::FloatLiteral { value, .. } => {
                let s = value.to_string();
                if s.contains('.') {
                    s
                } else {
                    format!("{}.0", s)
                }
            }
            Expr::StringLiteral { value, .. } => {
                format!("\"{}\".to_string()", value.replace('"', "\\\""))
            }
            Expr::InterpolatedString { parts, .. } => {
                // Generate format! macro
                let mut format_str = String::new();
                let mut args = Vec::new();
                for part in parts {
                    match part {
                        StringPart::Literal(s) => format_str.push_str(s),
                        StringPart::Expr(e) => {
                            format_str.push_str("{}");
                            args.push(self.generate_expr(e)?);
                        }
                    }
                }
                if args.is_empty() {
                    format!("\"{}\"", format_str)
                } else {
                    format!("format!(\"{}\", {})", format_str, args.join(", "))
                }
            }
            Expr::BoolLiteral { value, .. } => value.to_string(),
            Expr::CharLiteral { value, .. } => format!("'{}'", value),
            Expr::Identifier { name, .. } => name.clone(),
            Expr::Path { segments, .. } => {
                let parts: Vec<&str> = segments.iter().map(|s| s.node.as_str()).collect();
                parts.join("::")
            }
            Expr::Binary {
                left, op, right, ..
            } => {
                let left_str = self.generate_expr(left)?;
                let right_str = self.generate_expr(right)?;
                let op_str = self.binary_op_to_rust(op);
                format!("({} {} {})", left_str, op_str, right_str)
            }
            Expr::Unary { op, operand, .. } => {
                let operand_str = self.generate_expr(operand)?;
                let op_str = self.unary_op_to_rust(op);
                format!("{}{}", op_str, operand_str)
            }
            Expr::Call { callee, args, .. } => {
                let callee_str = self.generate_expr(callee)?;
                let args_str: Result<Vec<_>, _> =
                    args.iter().map(|e| self.generate_expr(e)).collect();
                let args_joined = args_str?.join(", ");
                format!("{}({})", callee_str, args_joined)
            }
            Expr::MethodCall {
                object,
                method,
                args,
                ..
            } => {
                let obj_str = self.generate_expr(object)?;
                let args_str: Result<Vec<_>, _> =
                    args.iter().map(|e| self.generate_expr(e)).collect();
                format!("{}.{}({})", obj_str, method.node, args_str?.join(", "))
            }
            Expr::FieldAccess { object, field, .. } => {
                let obj_str = self.generate_expr(object)?;
                // tomi.u has no ownership semantics, so clone field values
                // accessed through references (e.g. self.name) to avoid
                // borrow-checker issues in the generated Rust code.
                if matches!(**object, Expr::Identifier { ref name, .. } if name == "self") {
                    format!("{}.{}.clone()", obj_str, field.node)
                } else {
                    format!("{}.{}", obj_str, field.node)
                }
            }
            Expr::Index { object, index, .. } => {
                let obj_str = self.generate_expr(object)?;
                let idx_str = self.generate_expr(index)?;
                format!("{}[{}]", obj_str, idx_str)
            }
            Expr::Array { elements, .. } => {
                let elems_str: Result<Vec<_>, _> =
                    elements.iter().map(|e| self.generate_expr(e)).collect();
                format!("[{}]", elems_str?.join(", "))
            }
            Expr::Tuple { elements, .. } => {
                let elems_str: Result<Vec<_>, _> =
                    elements.iter().map(|e| self.generate_expr(e)).collect();
                format!("({})", elems_str?.join(", "))
            }
            Expr::StructInit { path, fields, .. } => {
                let path_str = self.generate_type_path(path)?;
                let fields_str: Result<Vec<_>, _> = fields
                    .iter()
                    .map(|f| {
                        if let Some(value) = &f.value {
                            let val_str = self.generate_expr(value)?;
                            Ok(format!("{}: {}", f.name.node, val_str))
                        } else {
                            Ok(f.name.node.clone())
                        }
                    })
                    .collect();
                format!("{} {{ {} }}", path_str, fields_str?.join(", "))
            }
            Expr::If {
                condition,
                then_block,
                elif_clauses,
                else_block,
                ..
            } => {
                let cond_str = self.generate_expr(condition)?;
                let then_str = self.generate_block(then_block)?;

                let mut result = format!("if {} {{\n{}}}", cond_str, then_str);

                for (elif_cond, elif_block) in elif_clauses {
                    let elif_cond_str = self.generate_expr(elif_cond)?;
                    let elif_block_str = self.generate_block(elif_block)?;
                    result.push_str(&format!(
                        " else if {} {{\n{}}}",
                        elif_cond_str, elif_block_str
                    ));
                }

                if let Some(else_block) = else_block {
                    let else_str = self.generate_block(else_block)?;
                    result.push_str(&format!(" else {{\n{}}}", else_str));
                }

                result
            }
            Expr::Match {
                scrutinee, arms, ..
            } => {
                let val_str = self.generate_expr(scrutinee)?;
                let mut result = format!("match {} {{\n", val_str);

                for arm in arms {
                    let pat_str = self.generate_pattern(&arm.pattern)?;
                    result.push_str("    ");
                    result.push_str(&pat_str);

                    if let Some(guard) = &arm.guard {
                        let guard_str = self.generate_expr(guard)?;
                        result.push_str(&format!(" if {}", guard_str));
                    }

                    result.push_str(" => ");
                    let body_str = self.generate_expr(&arm.body)?;
                    result.push_str(&body_str);
                    result.push_str(",\n");
                }

                result.push('}');
                result
            }
            Expr::Reference { is_mut, inner, .. } => {
                let inner_str = self.generate_expr(inner)?;
                if *is_mut {
                    format!("&mut {}", inner_str)
                } else {
                    format!("&{}", inner_str)
                }
            }
            Expr::Deref { inner, .. } => {
                let inner_str = self.generate_expr(inner)?;
                format!("*{}", inner_str)
            }
            Expr::Range {
                start,
                end,
                inclusive,
                ..
            } => {
                let start_str = start
                    .as_ref()
                    .map(|e| self.generate_expr(e))
                    .transpose()?
                    .unwrap_or_default();
                let end_str = end
                    .as_ref()
                    .map(|e| self.generate_expr(e))
                    .transpose()?
                    .unwrap_or_default();

                if *inclusive {
                    format!("{}..={}", start_str, end_str)
                } else {
                    format!("{}..{}", start_str, end_str)
                }
            }
            Expr::Lambda { params, body, .. } => {
                let params_str: Vec<String> = params.iter().map(|p| p.name.node.clone()).collect();
                let body_str = self.generate_expr(body)?;
                format!("|{}| {}", params_str.join(", "), body_str)
            }
            Expr::Await { inner, .. } => {
                let inner_str = self.generate_expr(inner)?;
                format!("{}.await", inner_str)
            }
            Expr::Try { inner, .. } => {
                let inner_str = self.generate_expr(inner)?;
                format!("{}?", inner_str)
            }
            Expr::Cast { expr, ty, .. } => {
                let expr_str = self.generate_expr(expr)?;
                let ty_str = self.generate_type(ty)?;
                format!("{} as {}", expr_str, ty_str)
            }
            Expr::Block { block, .. } => {
                let block_str = self.generate_block(block)?;
                format!("{{\n{}}}", block_str)
            }
        };
        Ok(result)
    }

    fn generate_stmt(&mut self, stmt: &Stmt) -> Result<String, CompileError> {
        let result = match stmt {
            Stmt::Let {
                is_mut,
                pattern,
                ty,
                value,
                ..
            } => {
                let mut s = String::from("let ");
                if *is_mut {
                    s.push_str("mut ");
                }
                s.push_str(&self.generate_pattern(pattern)?);

                if let Some(ty) = ty {
                    s.push_str(": ");
                    s.push_str(&self.generate_type(ty)?);
                }

                if let Some(val) = value {
                    s.push_str(" = ");
                    s.push_str(&self.generate_expr(val)?);
                }

                s.push(';');
                s
            }
            Stmt::Expr(expr) => {
                let expr_str = self.generate_expr(expr)?;
                // Block-like expressions don't need trailing semicolons
                match expr {
                    Expr::Match { .. } | Expr::If { .. } | Expr::Block { .. } => expr_str,
                    _ => format!("{};", expr_str),
                }
            }
            Stmt::Assignment {
                target, op, value, ..
            } => {
                let target_str = self.generate_expr(target)?;
                let op_str = self.assign_op_to_rust(op);
                let val_str = self.generate_expr(value)?;
                format!("{} {} {};", target_str, op_str, val_str)
            }
            Stmt::For {
                pattern,
                iterable,
                body,
                ..
            } => {
                let pat_str = self.generate_pattern(pattern)?;
                let iter_str = self.generate_expr(iterable)?;
                let body_str = self.generate_block(body)?;
                format!("for {} in {} {{\n{}}}", pat_str, iter_str, body_str)
            }
            Stmt::While {
                condition, body, ..
            } => {
                let cond_str = self.generate_expr(condition)?;
                let body_str = self.generate_block(body)?;
                format!("while {} {{\n{}}}", cond_str, body_str)
            }
            Stmt::Loop { body, .. } => {
                let body_str = self.generate_block(body)?;
                format!("loop {{\n{}}}", body_str)
            }
            Stmt::Return { value, .. } => {
                if let Some(val) = value {
                    let val_str = self.generate_expr(val)?;
                    format!("return {};", val_str)
                } else {
                    "return;".to_string()
                }
            }
            Stmt::Break { value, .. } => {
                if let Some(val) = value {
                    let val_str = self.generate_expr(val)?;
                    format!("break {};", val_str)
                } else {
                    "break;".to_string()
                }
            }
            Stmt::Continue { .. } => "continue;".to_string(),
            Stmt::TryCatch {
                try_block,
                handlers,
                finally_block,
                ..
            } => {
                // Rust doesn't have try-catch, so we'll generate a Result-based pattern
                // For now, generate a comment and the try block as-is
                let mut result = String::new();
                result.push_str("// try-catch block (exception handling)\n");
                result.push_str("{\n");
                result.push_str(&self.generate_block(try_block)?);
                result.push_str("}\n");

                for handler in handlers {
                    if let Some(ty) = &handler.exception_type {
                        let type_str = self.generate_type(ty)?;
                        result.push_str(&format!("// catch {}\n", type_str));
                    } else {
                        result.push_str("// catch all\n");
                    }
                    result.push_str("if false {\n"); // Placeholder - will be replaced with proper error handling
                    result.push_str(&self.generate_block(&handler.body)?);
                    result.push_str("}\n");
                }

                if let Some(finally) = finally_block {
                    result.push_str("// finally block\n");
                    result.push_str(&self.generate_block(finally)?);
                }

                result
            }
            Stmt::Raise { exception, .. } => {
                let expr_str = self.generate_expr(exception)?;
                // Generate panic! for now, could be Result::Err in future
                format!("panic!(\"{{}}\", {});", expr_str)
            }
        };
        Ok(result)
    }

    fn generate_block(&mut self, block: &Block) -> Result<String, CompileError> {
        let mut result = String::new();

        for stmt in &block.stmts {
            let stmt_str = self.generate_stmt(stmt)?;
            for line in stmt_str.lines() {
                result.push_str(&self.config.indent);
                result.push_str(line);
                result.push('\n');
            }
        }

        Ok(result)
    }

    fn generate_pattern(&mut self, pattern: &Pattern) -> Result<String, CompileError> {
        let result = match pattern {
            Pattern::Wildcard { .. } => "_".to_string(),
            Pattern::Identifier { is_mut, name, .. } => {
                if *is_mut {
                    format!("mut {}", name.node)
                } else {
                    name.node.clone()
                }
            }
            Pattern::Literal { value, .. } => self.generate_expr(value)?,
            Pattern::Tuple { elements, .. } => {
                let elems_str: Result<Vec<_>, _> =
                    elements.iter().map(|p| self.generate_pattern(p)).collect();
                format!("({})", elems_str?.join(", "))
            }
            Pattern::Struct {
                path, fields, rest, ..
            } => {
                let path_str = self.generate_type_path(path)?;
                let mut fields_str: Vec<String> = fields
                    .iter()
                    .map(|f| {
                        if let Some(pat) = &f.pattern {
                            let pat_str = self.generate_pattern(pat).unwrap_or_default();
                            format!("{}: {}", f.name.node, pat_str)
                        } else {
                            f.name.node.clone()
                        }
                    })
                    .collect();
                if *rest {
                    fields_str.push("..".to_string());
                }
                format!("{} {{ {} }}", path_str, fields_str.join(", "))
            }
            Pattern::Variant { path, data, .. } => {
                let path_str = self.generate_type_path(path)?;
                if let Some(data) = data {
                    let data_str = self.generate_pattern(data)?;
                    format!("{}({})", path_str, data_str)
                } else {
                    path_str
                }
            }
            Pattern::Slice { elements, rest, .. } => {
                let mut elems_str: Vec<String> = elements
                    .iter()
                    .map(|p| self.generate_pattern(p).unwrap_or_default())
                    .collect();
                if let Some(rest_pat) = rest {
                    let rest_str = self.generate_pattern(rest_pat)?;
                    elems_str.push(format!("{}..", rest_str));
                }
                format!("[{}]", elems_str.join(", "))
            }
            Pattern::Or { patterns, .. } => {
                let pats_str: Result<Vec<_>, _> =
                    patterns.iter().map(|p| self.generate_pattern(p)).collect();
                pats_str?.join(" | ")
            }
            Pattern::Range {
                start,
                end,
                inclusive,
                ..
            } => {
                let start_str = start
                    .as_ref()
                    .map(|e| self.generate_expr(e))
                    .transpose()?
                    .unwrap_or_default();
                let end_str = end
                    .as_ref()
                    .map(|e| self.generate_expr(e))
                    .transpose()?
                    .unwrap_or_default();
                if *inclusive {
                    format!("{}..={}", start_str, end_str)
                } else {
                    format!("{}..{}", start_str, end_str)
                }
            }
            Pattern::Binding { name, pattern, .. } => {
                let pat_str = self.generate_pattern(pattern)?;
                format!("{} @ {}", name.node, pat_str)
            }
        };
        Ok(result)
    }

    fn config(&self) -> &CodegenConfig {
        &self.config
    }

    fn set_config(&mut self, config: CodegenConfig) {
        self.config = config;
        self.writer = CodeWriter::with_indent(&self.config.indent);
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_rust_backend_basic() {
        let backend = RustBackend::new();
        assert_eq!(backend.config().indent, "    ");
    }
}
